name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clear any cached node_modules
        run: rm -rf ./node_modules

      - name: Install dependencies (with eslint)
        run: npm install

      - name: Fix permissions for node_modules/.bin
        run: chmod -R 755 ./node_modules/.bin

      - name: Run ESLint
        run: npx eslint .

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fix permissions for node_modules/.bin
        run: chmod -R 755 ./node_modules/.bin

      - name: Run tests
        run: npx jest --passWithNoTests

  build:
    name: Build the application
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

  deploy:
    name: Deploy the application
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to production
        run: |
          echo "Deployment process starts here"
